
controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'


app_public_homepage:
    path: /{_locale}
    controller: App\Controller\PublicHomepageController::index 
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'